root: /content/engagement_detector
data_root: /content/drive/MyDrive/DAiSEE_upload64
model: /content/drive/MyDrive/models
logs: /content/drive/MyDrive/logs
epochs: 100
steps: 50
val_steps: 20
batch_size: 32
